# Generated by Django 4.1.7 on 2023-03-24 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0002_rename_ideas_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='vote',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together={('voter', 'idea')},
        ),
        migrations.RemoveField(
            model_name='voter',
            name='type_vote',
        ),
    ]
